### ISSUE TITLE
Make artificial delay flag more obvious and off by default

### ISSUE THREAD

**Issue by yozlet** [launchdarkly/SupportService#115]
Currently, the `artifical_delay()` function is invoked by the `trial_duration` flag. Problems:

1. There's nothing in the name or description of `trial_duration` that mentions this effect
2. It's on by default, which meant that I spent ages trying to work out why my page loads were occasionally slow (see previous point)

Assuming that nobody's actively using this in demos, could we:
1. have a dedicated flag for `artifical_delay`
2. ... that is off by default

CCing @InTheCloudDan who created `artificial_delay()` (a month or two ago)

**Comment by InTheCloudDan** [comment]
#133 closes this
