### ISSUE TITLE
Dark-Theme no longer working 

### ISSUE THREAD

**Issue by dtacci** [launchdarkly/SupportService#117]
Since our latest SupServ updates Dark Theme is no longer working. Even if the rule is on for everyone with no additional rules, nothing appears in our dropdown.

**Comment by levlaz** [comment]
This works locally for me, but not on the production instance, which seems a bit strange.

**Comment by levlaz** [comment]
This is the strangest thing I've ever seen. When I enabled debug logging for this feature flag, it started to work for me on staging. No other code change was made. 

I also ran `apt-get update && upgrade` on the host but I don't believe that would have anything to do with this.

**Comment by levlaz** [comment]
@InTheCloudDan is it possible that this is related to the nginx cache?

**Comment by levlaz** [comment]
Some other notes, if you go to the route manually it works just fine. It is not showing up in the dropdown for whatever reason.

**Comment by InTheCloudDan** [comment]
@levlaz might have been? It's been disabled for a few days, and it looks like Dark Theme is working on my instance.
