### ISSUE TITLE
Update DB to Include Company

### ISSUE THREAD

**Issue by manuelPartida** [launchdarkly/SupportService#26]
Update the model to include a table for companies. Populate with a handful of companies that can be assigned to users upon creation

**Comment by levlaz** [comment]
@manuelPartida check out this library for easily making fixtures (i.e. fake data) we can use this in both test and prod. https://github.com/croach/Flask-Fixtures

**Comment by levlaz** [comment]
Actually, I am going to use https://github.com/joke2k/faker instead to make some fake data. It will be easier in the long run.
