### ISSUE TITLE
Jira Integration

### ISSUE THREAD

**Issue by dtacci** [launchdarkly/SupportService#29]
One commonly fielded question is Jira integration / Issue tracking, especially when it comes to sunsetting features / code clean-up. 

We should have a working Jira Integration in the Integrations tab to visually demonstrate how that would work to customers.

**Comment by dtacci** [comment]
@levlaz I logged into Jira to open a new webhook integration but couldn't add the API as I don't have admin privileges required to create new add-ons in Atlassian. Can you help with this? 

I want us to all have this integrated into our demo so we can point to a working example of the Jira webhook integration so we can field questions regarding managing technical debt.

**Comment by levlaz** [comment]
@dtacci can we de-prioritize this until we have all of the other stuff flushed out?

**Comment by dtacci** [comment]
We now have a Jira account for our SE team that we can use to demo this integration. Closing issue.
